language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4.1"
  - "4.2"
before_script:
  - "npm install -g jshint"
  - "npm install -g istanbul"
script:
  - "jshint"
  - "npm test"
after_script:
  - cat ./node_modules/coveralls/bin/coveralls.js